### PR TITLE
fix: :source_code_exclude_patterns support for OTP-28+

### LINKED ISSUE #951: Error reading config during `mix release` on elixir 1.19.2 + otp28.1+
### Issue Description

The `:source_code_exclude_patterns` config is resulting in the following error during `mix release`

```
** (Mix) Could not read configuration file. It has invalid configuration terms such as functions, references, and pids. Please make sure your configuration is made of numbers, atoms, strings, maps, tuples and lists. The following entries are wrong:

Application: :sentry
Key: :source_code_exclude_patterns
Value: [~r/\/_build\//, ~r/\/deps\//, ~r/\/priv\//, ~r/\/test\//]
```

### Reproduction Steps

run `mix release` on an app with sentry on elixir 1.19.2 + otp28.1+ 

### Expected Behavior

running `mix release`  should succeed 

### Actual Behavior

```
** (Mix) Could not read configuration file. It has invalid configuration terms such as functions, references, and pids. Please make sure your configuration is made of numbers, atoms, strings, maps, tuples and lists. The following entries are wrong:

Application: :sentry
Key: :source_code_exclude_patterns
Value: [~r/\/_build\//, ~r/\/deps\//, ~r/\/priv\//, ~r/\/test\//]
```

### Elixir Version

1.19.2

### SDK Version

11.0.4

### Integration and Its Version

_No response_

### Sentry Config

_No response_

### PR DESCRIPTION
**Pull request by solnic**
This fixes release builds for Phoenix apps under OTP 28+ that configure Sentry with `: source_code_exclude_patterns` option by adding support for a list of strings that get compiled to regexps later on.

## For people on OTP 28.1

All you need is to use `~r/foo/E` instead of `~r/foo/` in your config files. For example:

```elixir
config :sentry,
  enable_source_code_context: true,
  root_source_code_paths: [File.cwd!()],
  source_code_exclude_patterns: [~r/_build/E, ~r/deps/E, ~r/priv/E, ~r/test/E]
```

## For people on OTP 28.0

You can convert your regexps for `source_code_exclude_patterns` config to strings:

```elixir
config :sentry,
  enable_source_code_context: true,
  root_source_code_paths: [File.cwd!()],
  source_code_exclude_patterns: ["/_build/", "/deps/", "/priv/", "/test/"]
```

---

Without this fix things can break like this:

## OTP 28.1

Arc 2025-12-19 12 53 54

## OTP 28.0

image

---

Fixes #951

### CODE REVIEW

File: lib/sentry/config.ex [hunk 1]
```diff
@@ -425,13 +425,17 @@ defmodule Sentry.Config do
...
       doc: """
       A list of regular expressions used to determine which files to
-      exclude from source code context.
+      exclude from source code context. Each element can be either a compiled
+      `Regex` or a string pattern that will be compiled to a regex at runtime.
+
+      Using strings is required for OTP 28.0 compatibility, as compiled regexes
+      cannot be serialized in release config files.
+
+      If you're on OTP 28.1 or later, you must use `\E` modifier in your regexps.
```
Comment (whatyouhide) [inline lib/sentry/config.ex]: Why the backslash before the `E`? Shouldn't we say just `E`?

**Review by whatyouhide — APPROVED** [review]
