### PR TITLE
Periodically purge check-ins ETS table

### LINKED ISSUE #762: Periodically purge check-ins ETS table
> @nsweeting yep, you're right! I'll add some sweep functionality that clears the tables. 
> 
> @whatyouhide, is the best approach to clear the table -> remove any check-in ids that have a 'stop' or 'exception' event? or something like `memsup` to check the available RAM and then clear based on the oldest entries?
> 
> I'm going to reopen this to address what @nsweeting mentions. 

 _Originally posted by @savhappy in [#749](https://github.com/getsentry/sentry-elixir/issues/749#issuecomment-2264149450)_

Let's go with the GenServer that owns the table periodically sweeping it. Every ~30 seconds, it can send a message to itself, go through the all table and use `ets:select_delete` or something like that to remove all check-ins that are older than, say, 10 minutes. If needed we can add a timestamp to the check ins, I don't recall if we do that already.

### PR DESCRIPTION
**Pull request by savhappy**
-add sweep functionality to CheckInIDMappings ets table to clear out stale jobs
-add configurable option to corn integrations (TTL) for long standing jobs
-closes #762

### CODE REVIEW

File: lib/sentry/application.ex [hunk 1]
```diff
@@ -19,11 +19,13 @@ defmodule Sentry.Application do
         []
       end
 
+    integrations = Keyword.fetch!(config, :integrations)
```
Comment (whatyouhide) [inline lib/sentry/application.ex:22]:
```suggestion
    integrations_config = Keyword.fetch!(config, :integrations)
```

File: lib/sentry/config.ex [hunk 2]
```diff
@@ -2,6 +2,16 @@ defmodule Sentry.Config do
   @moduledoc false
 
   integrations_schema = [
+    ttl: [
```
Comment (whatyouhide) [inline lib/sentry/config.ex:5]: We cannot call this `:ttl` and put it at the top of the `:integrations` subschema: it's too generic. I would call this `:max_expected_check_in_time`.

Also, in the docs you need to explain the use case here: you need to explain that the SDK reports check-in starts and check-in ends, and with this key then you will stop reporting check-in ends if they come `:max_expected_check_in_time` *after* the check-in start.

Also, try to avoid leaking implementation details in the docs. Don't mention the ETS table or sweeping. You can say something like "if check-in ends come after this time then the SDK won't report them, and this is to avoid memory leaks" yada yada.

File: lib/sentry/config.ex [hunk 3]
```diff
@@ -2,6 +2,16 @@ defmodule Sentry.Config do
...
+      type: :integer,
+      default: 600_000,
+      doc: """
+      The time in milliseconds that a check-in id will live after it has been created.
+
+      For long running cron jobs, set ttl (time to live) to longest running job time in milliseconds.
+      This avoids jobs being sweeped from table before they've been completed. Defaults to ten minutes.
```
Comment (whatyouhide) [inline lib/sentry/config.ex:12]:
```suggestion
      This avoids jobs being sweeped from table before they've been completed.
```

nimble_options already documents the default you used in the `:default` key (try it with `mix docs`).

File: lib/sentry/integrations/check_in_id_mappings.ex [hunk 4]
```diff
@@ -5,30 +5,58 @@ defmodule Sentry.Integrations.CheckInIDMappings do
...
+    _ = :ets.select_delete(@table, match_spec)
+
+    schedule_sweep(state)
+    {:noreply, state}
+  end
+
+  ## Helpers
+
+  defp schedule_sweep(ttl_millisec) do
+    Process.send_after(self(), {:sweep, ttl_millisec}, @sweep_interval_millisec)
```
Comment (whatyouhide) [inline lib/sentry/integrations/check_in_id_mappings.ex:55]: Do you need to send over the `ttl_millisec` if it's the state of the GenServer anyway?

**Review by whatyouhide — COMMENTED** [review]
Left a few preliminary comments, but it's a great start. 🙃

File: lib/sentry/integrations/check_in_id_mappings.ex (hunk 4 above)
Comment (savhappy) [reply lib/sentry/integrations/check_in_id_mappings.ex:55]: Nope! Thx for pointing that out!

File: lib/sentry/config.ex
Comment (savhappy) [inline lib/sentry/config.ex:1]: Elaborate in here or somewhere else in docs on what check-in id is? @whatyouhide

File: lib/sentry/integrations/check_in_id_mappings.ex (hunk 4 above)
Comment (savhappy) [reply lib/sentry/integrations/check_in_id_mappings.ex]: Okay by removing this meant I had to make this genserver configurable for testing since we're testing both a singleton and isolated process. So this caused some extra changes in the code

File: lib/sentry/application.ex [hunk 5]
```diff
@@ -19,11 +19,14 @@ defmodule Sentry.Application do
...
 
+    integrations_config = Keyword.fetch!(config, :integrations)
+
     children =
       [
         {Registry, keys: :unique, name: Sentry.Transport.SenderRegistry},
         Sentry.Dedupe,
-        Sentry.Integrations.CheckInIDMappings
+        {Sentry.Integrations.CheckInIDMappings,
+         [max_expected_check_in_time: integrations_config[:max_expected_check_in_time]]}
```
Comment (whatyouhide) [inline lib/sentry/application.ex:29]: We always expect this:

```suggestion
         [max_expected_check_in_time: Keyword.fetch!(integrations_config, :max_expected_check_in_time]}
```

File: lib/sentry/config.ex [hunk 6]
```diff
@@ -2,6 +2,18 @@ defmodule Sentry.Config do
   @moduledoc false
 
   integrations_schema = [
+    max_expected_check_in_time: [
+      type: :integer,
+      default: 600_000,
+      doc: """
+      The time in milliseconds that a check-in id will live after it has been created.
```
Comment (whatyouhide) [inline lib/sentry/config.ex:9]:
```suggestion
      The time in milliseconds that a check-in ID will live after it has been created.
```

File: lib/sentry/config.ex [hunk 7]
```diff
@@ -2,6 +2,18 @@ defmodule Sentry.Config do
...
+
+      The SDK reports the start and end of each check-in. However, to optimize performance and prevent
+      potential memory issues, if a check-in end event is reported after the specified `max_expected_check_in_time`,
+      the SDK will not report it. This behavior helps manage resource usage effectively while still providing necessary
+      tracking for your jobs.
```
Comment (whatyouhide) [inline lib/sentry/config.ex:14]: @savhappy elaborate here what a check-in is and why this option is necessary

File: test/sentry/check_in_id_mappings_test.exs [hunk 8]
```diff
@@ -0,0 +1,30 @@
...
+        start:
+          {CheckInIDMappings, :start_link, [[max_expected_check_in_time: 0, name: TestMappings]]}
+      }
+
+      pid = start_supervised!(child_spec)
+
+      CheckInIDMappings.lookup_or_insert_new(cron_key)
+      assert :ets.lookup(@table, cron_key) != []
+
+      Process.sleep(5)
```
Comment (whatyouhide) [inline test/sentry/check_in_id_mappings_test.exs:23]: Why sleep here?

Comment (savhappy) [reply test/sentry/check_in_id_mappings_test.exs:23]: We need to sleep to allow the `:sweep` message to be processed by the target process so that the final assertion accurately reflects the updated state of the ETS table. Otherwise, it returns the key/value pair before being deleted.

File: lib/sentry/config.ex [hunk 9]
```diff
@@ -2,6 +2,20 @@ defmodule Sentry.Config do
...
+      default: 600_000,
+      doc: """
+      The time in milliseconds that a check-in ID will live after it has been created.
+
+      The SDK reports the start and end of each check-in. A check-in is used to track the
+      progress of a specific check-in event associated with cron job telemetry events that are a part
+      of the same job. However, to optimize performance and prevent potential memory issues,
+      if a check-in end event is reported after the specified `max_expected_check_in_time`,
+      the SDK will not report it. This behavior helps manage resource usage effectively while still
+      providing necessary tracking for your jobs.
```
Comment (whatyouhide) [inline lib/sentry/config.ex:16]:
```suggestion
      providing necessary tracking for your jobs.
      
      *Available since 10.6.3*.
```

File: test/sentry/check_in_id_mappings_test.exs (hunk 8 above)
Comment (whatyouhide) [reply test/sentry/check_in_id_mappings_test.exs:23]: If you call `:sys.get_state(pid)`, you are making a sync call to the GenServer. Since messages are ordered, you are guaranteed that by the time the GenServer replies to the `:sys.get_state/1` call then the `:sweep` message will have been processed. So, you can remove this 🙃

**Review by whatyouhide — COMMENTED** [review]
Last two comments and we're good to go!

File: test/sentry/check_in_id_mappings_test.exs (hunk 8 above)
Comment (savhappy) [reply test/sentry/check_in_id_mappings_test.exs:23]: Maybe I'm missing something? When I remove the sleep it returns the pair and the final assert fails

```   test/sentry/check_in_id_mappings_test.exs:9
     Assertion with == failed
     code:  assert :ets.lookup(@table, cron_key) == []
     left:  [{"quantum_123", "ec2ded4d0c1a43b580d2e567396e3bee", 1723541054291}]
     right: []
     stacktrace:
       test/sentry/check_in_id_mappings_test.exs:27: (test)
```

Comment (whatyouhide) [reply test/sentry/check_in_id_mappings_test.exs:23]: Ok no rush I can debug this locally.

**Review by whatyouhide — APPROVED** [review]

File: lib/sentry/config.ex [hunk 10]
```diff
@@ -2,6 +2,22 @@ defmodule Sentry.Config do
...
+
```
Comment (whatyouhide) [inline lib/sentry/config.ex:17]:
```suggestion

```
