### PR TITLE
Logger Backend improvements

### LINKED ISSUE #383: Exceptions with breadcrumbs using Sentry.LoggerBackend
### Environment

* Elixir version (elixir -v): All 
* Erlang/OTP version (erl): all 
* Sentry version (mix deps): 7.x
* Operating system: All

### Description
When a process crashes or an exception is raised sentry-elixir will capture the exception correctly. However, if you use breadcrumbs or other context sentry-elixir will not pass this correctly.  

As I understand the code we are using the Process dictionary to hold all context.  The problem comes up when you are utilizing `Sentry.LoggerBackend` as your logger backend.  The logger and the process the exception occurred in are not the same resulting in no context being sent.  

### Expected Behavior
Context will be passed correctly when errors and exceptions happen.  

### Actual Behavior
Context is lost because the logger is a different process.

### Steps to Reproduce
```elixir
defmodule Test.MimicGenserver do
  alias GenServer
  use GenServer

  def start_link(_) do
    GenServer.start_link(__MODULE__, %{}, name: __MODULE__)
  end

  def init(_) do
    {:ok, %{}}
  end

  def error, do: GenServer.call(__MODULE__, :error)

  def terminate(reason, state) do
    :normal
  end

  def handle_call(:error, _from, _state) do
    Sentry.Context.add_breadcrumb(%{category: "will not show"})
    {:stop, "crash", :error, nil}
  end
end

defmodule ClientTest do
  use ExUnit.Case

  alias Test.MimicGenserver
  import ExUnit.CaptureLog

  test "if breadcrumb exists" do
    # assert {:ok, %{"test" => "test"}} = Client.make_request(request())
    bypass = Bypass.open()
    pid = self()
    start_supervised!(MimicGenserver)

    Bypass.expect(bypass, fn conn ->
      {:ok, body, conn} = Plug.Conn.read_body(conn)
      decoded_body = Jason.decode!(body)
      assert body =~ "will not show"
      send(pid, "API called")
      Plug.Conn.resp(conn, 200, ~s<{"id": "340"}>)
    end)

    Application.put_env(:sentry, :dsn, "http://public:secret@localhost:#{bypass.port}/1")

    capture_log(fn ->
      MimicGenserver.error()
      assert_receive "API called"
    end)
  end

end

```

### Solution?
I threw together a solution last night that I would be willing to clean up a bit more and submit if you are open to PR's and adding another dependency.  

My idea is to move away from the process dictionary and to utilize something like `cachex` as the context store.  When the context is set we could obtain the PID of the process and store that as the key in cachex.  This would allow us to utilize 98% of the context module that's in place.  When the exception is logged we can grab the PID from the metadata allowing us to obtain the context for the specific process.  Allowing us to pass the context with the error.  

The only limitation I can think of with this solution is how we would monitor the process and delete keys when the process is killed normally.  

Other than that I think this could be a major version bump as you would need to also incorporate a supervisor tree and start sentry as an application within your application.  If you didnt want to do a major version bump we could possibly break this out in to another module and switch between the process dictionary context and cachex context depending on if a user mounted the application. 

### Final thoughts...
You  may already have plans to add this or have another idea.  Just wanted to throw some thoughts your way in case you need a helping hand to implement this.  It's something I feel we are going to need to do for multiple apps we use. That or we may implement some custom functionality that mimics the above.  Utilizing a new logger, custom context module and a custom before_send event. 

Thanks for the work!  The code was extremely easy to follow and took minimal effort to understand.

### LINKED ISSUE #397: Multiple reports per exception
### Environment

* Elixir version (elixir -v): 1.10.3
* Erlang/OTP version (erl): 23.0.2
* Sentry version (mix deps): 7.2.4
* Operating system: Linux
* Is this an umbrella application?: No
* Release type (Distillery, mix release, Mix, etc.): mix release

### Description

Every exception in a plug or controllers gets reported three times.

### Expected Behavior

A single event per exception

### Actual Behavior

There's three Sentry events per exception, with varying amounts of metadata:

* One report has the usual metadata, respecting header scrubber setting
* Another one looks similar, but includes sensitive headers (it's not scrubbed)
* The final one is missing almost all metadata

I believe these come from Sentry.Plug, Sentry.Phoenix.Endpoint, and Sentry.LoggerBackend respectively.

### Steps to Reproduce

Setup a new Phoenix app with:

* Sentry.Plug
* Sentry.Phoenix.Endpoint
* Sentry.LoggerBackend

then add `raise "boom"` inside a controller and try to load the page.

I suspect the Phoenix and Cowboy versions are important. This is with Phoenix 1.5.3 and Cowboy 2.8.0. The LoggerHandler seems to check for Cowboy2Handler in the stack trace, which isn't present. Here'a sample `:crash_reason` as received by the logger backend:

```
[
   {MyAppWeb.TheController, :index, 2,
    [file: 'lib/myapp_web/controllers/the_controller.ex', line: 22]},
   {MyAppWeb.TheController, :action, 2,
    [file: 'lib/myapp_web/controllers/the_controller.ex', line: 1]},
   {MyAppWeb.TheController, :phoenix_controller_pipeline, 2,
    [file: 'lib/myapp_web/controllers/the_controller.ex', line: 1]},
   {Phoenix.Router, :__call__, 2, [file: 'lib/phoenix/router.ex', line: 352]},
   {MyAppWeb.Router, :call, 2, [file: 'lib/plug/error_handler.ex', line: 65]},
   {MyAppWeb.Endpoint, :plug_builder_call, 2,
    [file: 'lib/myapp_web/endpoint.ex', line: 1]},
   {MyAppWeb.Endpoint, :"call (overridable 3)", 2,
    [file: 'lib/plug/debugger.ex', line: 132]},
   {MyAppWeb.Endpoint, :call, 2,
    [file: 'lib/myapp_web/endpoint.ex', line: 1]}
 ]
```

This is similar to https://github.com/getsentry/sentry-elixir/issues/374.

I'm not sure what causes the duplication between Sentry.Phoenix.Endpoint and Sentry.Plug.

### PR DESCRIPTION
**Pull request by mitchellhenke**
With significant initial work from @josevalim 

- Ignores Plug/Cowboy process crashes by excluding by Logger `:domain`
- Allows sending all messages received by Logger
- Non-Sentry metadata to be included in reports is now specified by a list of keys

closes #383, closes #397

### CODE REVIEW

File: lib/sentry/logger_backend.ex [hunk 1]
```diff
@@ -128,27 +97,54 @@ defmodule Sentry.LoggerBackend do
...
+        extra: %{logger_metadata: logger_metadata(meta, state), logger_level: level},
+        result: :none
+      ] ++ Map.to_list(sentry)
+
+    case meta[:crash_reason] do
+      {exception, stacktrace} when is_list(stacktrace) ->
+        Sentry.capture_exception(exception, [stacktrace: stacktrace] ++ opts)
+
+      reason when is_atom(reason) and not is_nil(reason) ->
+        Sentry.capture_exception(reason, opts)
```
Comment (josevalim) [inline lib/sentry/logger_backend.ex:115]: Do you know when this would ever be the case?

File: lib/sentry/logger_backend.ex [hunk 2]
```diff
@@ -128,27 +97,54 @@ defmodule Sentry.LoggerBackend do
...
+    end
+  end
 
-    %{
-      state
-      | level: level,
-        include_logger_metadata: include_logger_metadata,
-        ignore_plug: ignore_plug
-    }
+  defp get_sentry_from_callers([head | tail]) do
```
Comment (josevalim) [inline lib/sentry/logger_backend.ex:130]:
```suggestion
  defp get_sentry_from_callers([head | tail]) when is_pid(head) do
```

Otherwise a list of `callers: [1]` would make it fail.

File: test/logger_backend_test.exs [hunk 3]
```diff
@@ -205,68 +211,165 @@ defmodule Sentry.LoggerBackendTest do
...
+      Sentry.TestGenServer.add_logger_metadata(pid, :atom, :atom)
+      Sentry.TestGenServer.add_logger_metadata(pid, :number, 43)
+      Sentry.TestGenServer.add_logger_metadata(pid, :list, [])
+      Sentry.TestGenServer.invalid_function(pid)
+      assert_receive "terminating"
+      assert_receive "API called"
+    end)
+  end
+
+  test "sends all messages if capture_log_messages is true" do
```
Comment (josevalim) [inline test/logger_backend_test.exs:302]: Let's add a test that the level is respected. For example, Logger.debug is never sent. :)

File: lib/sentry/logger_backend.ex (hunk 2 above)
Comment (josevalim) [reply lib/sentry/logger_backend.ex:130]: We should probably add a test for malformed callers. :)

File: lib/sentry/logger_backend.ex (hunk 1 above)
Comment (mitchellhenke) [reply lib/sentry/logger_backend.ex:115]: yeah, I meant to put some details in the PR when I made these changes, but forgot.

A few of the cases don't match `%{__exception__: true}`. Specifically:

https://github.com/getsentry/sentry-elixir/pull/403/files#diff-c895426ce24017d1803054d94e4d71c3L41 crash_reason is:
`crash_reason: {{:bad_return_value, "I am throwing"}, []}`

https://github.com/getsentry/sentry-elixir/pull/403/files#diff-c895426ce24017d1803054d94e4d71c3L69 is:
`crash_reason: {:bad_exit, []}`

https://github.com/getsentry/sentry-elixir/pull/403/files#diff-c895426ce24017d1803054d94e4d71c3L155:
`crash_reason: {{:timeout,
    {GenServer, :call, [#PID<0.738.0>, {:sleep, 20}, 1]}},
   [
     {GenServer, :call, 3, [file: 'lib/gen_server.ex', line: 1023]},
     {Task.Supervised, :invoke_mfa, 2,
      [file: 'lib/task/supervised.ex', line: 90]},
     {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}
   ]}`

They eventually get passed into `Exception.normalize`.

Comment (josevalim) [reply lib/sentry/logger_backend.ex:115]: @mitchellhenke none of those are exceptions though. They are all exits. And I don't think we should treat them as exceptions. If you really want those reported, then I would recommend enabling `capture_log_message` by default and then maybe set the default level to `:error`?

File: test/logger_backend_test.exs (hunk 3 above)
Comment (mitchellhenke) [reply test/logger_backend_test.exs:302]: Done!

File: lib/sentry/logger_backend.ex (hunk 1 above)
Comment (josevalim) [inline lib/sentry/logger_backend.ex:115]: You can try this instead:

```elixir
defmodule Sentry.CrashError do
  defstruct [:message]

  def exception({:nocatch, reason}) do
    %Sentry.CrashError{message: Exception.format_banner(:throw, reason, [])}
  end

  def exception(reason) do
    %Sentry.CrashError{message: Exception.format_banner(:exit, reason, [])}
  end
end
```

and then here you do:

```suggestion
      {%_{__exception__: true} = exception, stacktrace} when is_list(stacktrace) ->
        Sentry.capture_exception(exception, [stacktrace: stacktrace] ++ opts)

      {other, stacktrace} when is_list(stacktrace) ->
        Sentry.capture_exception(Sentry.CrashError.exception(other), [stacktrace: stacktrace] ++ opts)
```
