### PR TITLE
Ensure stacktrace is list in LoggerBackend

### LINKED ISSUE #380: Sentry.LogggerBackend crashes when a genserver call times out
### Environment

* Elixir version (elixir -v): Elixir 1.9.4 (compiled with Erlang/OTP 21)
* Erlang/OTP version (erl): Erlang/OTP 22 [erts-10.5.6] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
* Sentry version (mix deps): 7.2.1
* Operating system: Ubuntu

### Description

Sentry.LoggerBackend crashes when a timeout is encountered on a GenServer call()

The following is a snippet from my logs. 

* A request arrives and the server times out handling it. Then Sentry is seen to crash
```
Request: POST /graphql
** (exit) exited in: GenServer.call(Shift.GenServer, {:get_shift_segments, %{:__absinthe_plug__ => %{uploads: %{}}, :pubsub => MyApp.Endpoint, :request_id => "FeGPuzwNBAzjOnIAACAk"}}, 10000)
    ** (EXIT) time out
[error] :gen_event handler Sentry.LoggerBackend installed in Logger terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for {GenServer, :call, [Shift.GenServer, {:get_shift_segments, %{:__absinthe_plug__ => %{uploads: %{}}, :pubsub => MyApp.Endpoint, :request_id => "FeGPuzwNBAzjOnIAACAk"}}, 10000]} of type Tuple. This protocol is implemented for the following type(s): Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.PrepareStream, DBConnection.Stream, Timex.Interval, Stream, Range, Date.Range, HashDict, GenEvent.Stream, List, HashSet, File.Stream, IO.Stream, Map, Function, MapSet
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:366: Enum.any?/2
    (sentry) lib/sentry/logger_backend.ex:82: Sentry.LoggerBackend.handle_event/2
    (stdlib) gen_event.erl:577: :gen_event.server_update/4
    (stdlib) gen_event.erl:559: :gen_event.server_notify/4
    (stdlib) gen_event.erl:300: :gen_event.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

I put in an IO inspect in logger_backend.ex at handle_event/2 to see what the "meta" variable holds:

```
"Got meta [crash_reason: {:timeout, {GenServer, :call, [Shift.GenServer, {:get_shift_segments, %{:__absinthe_plug__ => %{uploads: %{}}, :pubsub => MyApp.Endpoint, :request_id => \"FeGPuwNVo-wbA-MAACKh\"}, 10000]}}, pid: #PID<0.1378.0>]"
```

### Expected Behavior

No crashing

### Actual Behavior

logger backend has problems with this case and crashes

### Steps to Reproduce

* A GenServer.call() times out

### PR DESCRIPTION
**Pull request by mitchellhenke**
Closes #380

### CODE REVIEW

File: lib/sentry/logger_backend.ex [hunk 1]
```diff
@@ -93,6 +93,11 @@ defmodule Sentry.LoggerBackend do
           Sentry.capture_exception(reason, opts)
         end
 
+      {{_reason, stacktrace}, {_m, _f, args}} when is_list(stacktrace) and is_list(args) ->
+        # Cowboy stuff
+        # https://github.com/ninenines/cowboy/blob/master/src/cowboy_stream_h.erl#L148-L151
```
Comment (alizain) [inline lib/sentry/logger_backend.ex]: Hey @mitchellhenke, will you be adding code to capture this case in Sentry as well?

Comment (mitchellhenke) [reply lib/sentry/logger_backend.ex]: Mentioned in https://github.com/getsentry/sentry-elixir/issues/380#issuecomment-585900553, but the events are for the same crash, so reporting twice would be a duplicate 🙂

Comment (alizain) [reply lib/sentry/logger_backend.ex]: Ah, got it. Thanks!
